/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '<template>': typeof import('./src/components/<template>.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterNav: typeof import('./src/components/FooterNav.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HeroButton: typeof import('./src/components/HeroButton.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
