module.exports = {
  "primary-120": "rgb(var(--color-primary-120) / <alpha-value>)",
  "primary-100": "rgb(var(--color-primary-100) / <alpha-value>)",
  "primary-80": "rgb(var(--color-primary-80) / <alpha-value>)",
  "primary-60": "rgb(var(--color-primary-60) / <alpha-value>)",
  "primary-40": "rgb(var(--color-primary-40) / <alpha-value>)",
  "primary-tint": "rgb(var(--color-primary-tint) / <alpha-value>)",
  "semantic-success-120": "rgb(var(--color-success-120) / <alpha-value>)",
  "semantic-success-100": "rgb(var(--color-success-100) / <alpha-value>)",
  "semantic-success-20": "rgb(var(--color-success-20) / <alpha-value>)",
  "semantic-success-10": "rgb(var(--color-success-10) / <alpha-value>)",
  "semantic-info-120": "rgb(var(--color-info-120) / <alpha-value>)",
  "semantic-info-100": "rgb(var(--color-info-100) / <alpha-value>)",
  "semantic-info-20": "rgb(var(--color-info-20) / <alpha-value>)",
  "semantic-info-10": "rgb(var(--color-info-10) / <alpha-value>)",
  "semantic-error-120": "rgb(var(--color-error-120) / <alpha-value>)",
  "semantic-error-100": "rgb(var(--color-error-100) / <alpha-value>)",
  "semantic-error-20": "rgb(var(--color-error-20) / <alpha-value>)",
  "semantic-error-10": "rgb(var(--color-error-10) / <alpha-value>)",
  "netural-background": "rgb(var(--color-netural-background) / <alpha-value>)",
  "netural-100": "rgb(var(--color-netural-100) / <alpha-value>)",
  "netural-80": "rgb(var(--color-netural-80) / <alpha-value>)",
  "netural-60": "rgb(var(--color-netural-60) / <alpha-value>)",
  "netural-40": "rgb(var(--color-netural-40) / <alpha-value>)",
  "netural-10": "rgb(var(--color-netural-10) / <alpha-value>)",
  "netural-0": "rgb(var(--color-netural-0) / <alpha-value>)",
};